version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-jammy

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      - run:
          name: Start Grunt Server
          command: |
            npx grunt &
            echo $! > grunt.pid  # Save the PID
            sleep 5  # Let it start
            timeout 30 sh -c 'until curl -sSf http://localhost:8000; do sleep 1; done'
      
      - run:
          name: Run Playwright tests
          command: npx playwright test
          no_output_timeout: 10m

      - run:
          name: Stop Grunt Server
          when: always
          command: |
            if [ -f grunt.pid ]; then
              kill $(cat grunt.pid) || true
            fi

      - store_artifacts:
          path: test-results/
          destination: playwright-test-results

workflows:
  version: 2
  test:
    jobs:
      - test
