version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-jammy # Official Playwright image with all deps

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      - run:
          name: Start Grunt server in background
          command: |
            npx grunt &
            sleep 15  # Wait for server to fully start
          background: true

      - run:
          name: Wait for server to be ready
          command: |
            timeout 30 sh -c 'until curl -f http://localhost:8000; do sleep 1; done'

      - run:
          name: Run Playwright tests
          command: npx playwright test
          no_output_timeout: 10m

      - store_artifacts:
          path: test-results/
          destination: playwright-test-results

workflows:
  version: 2
  test:
    jobs:
      - test
